name: Build Docker Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-python-app .
